# Generated by Django 2.2.4 on 2020-04-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20200410_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='ObjectViewed',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
