# Generated by Django 2.2.4 on 2020-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200312_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='linetotal',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100),
        ),
    ]
