# Generated by Django 2.2.4 on 2020-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200318_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='carts.Cart'),
        ),
    ]
