# Generated by Django 2.2.4 on 2020-03-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestEmail',
        ),
    ]
