# Generated by Django 2.2.4 on 2020-04-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(default=False, on_delete='CASCADE', to='Billing.BillingProfile'),
        ),
    ]
