# Generated by Django 2.2.4 on 2020-04-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_billing_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='Billing.BillingProfile'),
        ),
    ]
