# Generated by Django 2.2.4 on 2020-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20200319_1151'),
        ('Billing', '0001_initial'),
        ('Orders', '0003_auto_20200409_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_profile',
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('active', models.BooleanField(default=True)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='Billing.BillingProfile')),
                ('cart', models.ForeignKey(on_delete='CASCADE', to='carts.Cart')),
            ],
        ),
    ]
