# Generated by Django 2.2.4 on 2020-04-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20200319_1151'),
        ('Orders', '0005_auto_20200409_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='carts.CartItem'),
        ),
    ]
